# from .models import Sport

# SPORTS: list[Sport] = [
#     Sport(id="1", slug="football", name="Football"),
#     Sport(id="2", slug="basketball", name="Basketball"),
#     Sport(id="4", slug="ice-hockey", name="Ice Hockey"),
#     Sport(id="5", slug="tennis", name="Tennis"),
#     Sport(id="6", slug="handball", name="Handball"),
#     Sport(id="11", slug="motorsport", name="Motorsport"),
#     Sport(id="12", slug="rugby", name="Rugby"),
#     Sport(id="15", slug="bandy", name="Bandy"),
#     Sport(id="19", slug="snooker", name="Snooker"),
#     Sport(id="20", slug="table-tennis", name="Table Tennis"),
#     Sport(id="22", slug="darts", name="Darts"),
#     Sport(id="23", slug="volleyball", name="Volleyball"),
#     Sport(id="26", slug="waterpolo", name="Waterpolo"),
#     Sport(id="29", slug="futsal", name="Futsal"),
#     Sport(id="31", slug="badminton", name="Badminton"),
#     Sport(id="34", slug="beach-volley", name="Beach Volleyball"),
#     Sport(id="62", slug="cricket", name="Cricket"),
#     Sport(id="63", slug="american-football", name="American Football"),
#     Sport(id="65", slug="cycling", name="Cycling"),
#     Sport(id="72", slug="esports", name="Esports"),
#     Sport(id="76", slug="mma", name="MMA"),
#     Sport(id="109", slug="minifootball", name="Minifootball"),
# ]

# RANKING_IDS = {
#     "uefa-countries": 1,
#     "fifa-rankings": 2,
#     "rugby-union-rankings": 3,
#     "rugby-league-rankings": 4,
#     "atp-rankings": 5,
#     "wta-rankings": 6,
#     "atp-rankings-live": 7,
#     "wta-rankings-live": 8,
#     "uefa-clubs": 9,
#     "ufc-flyweight": 11,
#     "ufc-bantamweight": 12,
#     "ufc-featherweight": 13,
#     "ufc-lightweight": 14,
#     "ufc-welterweight": 15,
#     "ufc-middleweight": 16,
#     "ufc-light-heavyweight": 17,
#     "ufc-heavyweight": 18,
#     "ufc-womens-strawweight": 19,
#     "ufc-womens-flyweight": 20,
#     "ufc-womens-bantamweight": 21,
#     "ufc-womens-featherweight": 22,
#     "utr-men": 34,
#     "utr-women": 35,
# }
