site_name: sport-index Documentation
repo_url: https://github.com/JolanDUBOIS/sport-index
repo_name: JolanDUBOIS/sport-index

theme:
  name: material
  features:
    - navigation.version
    - navigation.sections
    - navigation.expand

plugins:
  - search
  - mkdocstrings

nav:
  - Home: index.md
  - API Reference: api.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  version:
    provider: mike